### ISSUE TITLE
tools/find_lv1_call.idc and tools/find_lv1_call.idc always generate conflicts when merge

### ISSUE THREAD

**Issue by hobby-lc** [kakaroto/PL3#13]
Any webpage/document show how to resolve that? Thanks

**Comment by kakaroto** [comment]
what conflict? without any information how can i understand what the error is?

**Comment by hobby-lc** [comment]
Sorry, the conflict is about the CRLF again.
I config my local git by following the github help guide.
http://help.github.com/dealing-with-lineendings/

I guest I should disable the fix end-line config.

**Comment by kakaroto** [comment]
humm.. I scp-ed the files from windows into my linux machine and committed from linux.. maybe that's why it wasn't "auto-fixed" for you.. I'm not sure.
I'll dos2unix the files just in case and see if there's any diff.

**Comment by kakaroto** [comment]
ok, just tried a dos2unix and no changes, so the files were already good.. I don't know why you'd get merge conflicts.. I'm not sure how git reacts to CRLF on windows.. never used git on windows.. if you find something, let me know.
For now, closing the issue.
