### ISSUE TITLE
Payload for jailbreaking 3.21 firmware. Does it work in NTSC-J console ?

### ISSUE THREAD

**Issue by ripclaw** [kakaroto/PL3#17]
Just wanted to confirm if the payload to jailbreak 3.21 firmware is known to work in a NTSC-J console.
The PS3 being used is a 60GB NTSC-J Fat & the dongle is the red one from ps3usbjailbreak.com, flashed appropriately.
Either of the two symptoms can be seen after the jailbreak procedure:
1. Screen stays blank (and wireless controller does not register with the PS3)
2. Animated background is shown in the screen, but without menus (and it was also observed that the wireless controller registers with the console, possibly indicating that the blue-tooth stack is up in the PS3!)
The jailbreak LED goes green on both of the cases!! (indicating success!!!)
Could you throw some light into the issue ?

**Comment by fungos** [comment]
I don't know if there is difference in firmwares 3.21. But this dongle uses PL3? Before upgrading to 3.41 I tested 3.21 and it was working after my last commit (fix in some addresses). Anyway, it is better to upgrade to 3.41, I will gain nothing staying with 3.21.

**Comment by kakaroto** [comment]
I don't think there's a difference.. but I'm not sure, it's possible that the 3.21 port isn't working anymore. So I'd suggest you just upgrade to 3.41 like fungos suggested.

**Comment by CrashSerious** [comment]
What payload are you using? I got that (item 2) yesterday on 3.15 with either the HV or SC (Not SC+HV) trace payloads (I forget which, it was late)... ensure you are using the default payload.

fungos and kakaroto are right, you're not gaining anything by stay on below 3.41 unless possibly you are on or before 3.15 with a FAT. (just my 2 cents)

**Comment by kakaroto** [comment]
A crash can be caracterized by either one of these situations :
1 - black screen
2 - A frozen image
3 - The 'wave' of the background of the xmb still moving with those pseudo-sparkles in the background (usually with a slower speed than normal).

So when you get the animated background but no menus (no xmb), it just means it froze.
@CrashSerious: I know that the HV+SC will definitely cause a crash simply because of the huge amount of data being transfered at once, and race conditions start happening (especially when the ps3 wants to start sending its own dhcp and upnp requests). I know that the HV payload still does work, but could sometimes crash (it's just rarer than with HV+SC).. it still sends between 500KB to 1MB of data per second...so it's very intensive!

**Comment by ripclaw** [comment]
@kakaroto - Thanks for sharing the crash behaviors. Looks like I can confirm that the PS3 or some app is crashing/looping because it shows either "1- black screen' or "3- wave-background-pseudo-sparkles". every time :-(
But one thing that keeps me wondering is that the JB LED still turns green. So somehow the payload is able to trigger a communication to the JB stick after infecting the PS3. 
And by the way, I have been using the PS3 with Internet/Network disabled. Also, neither Ethernet cable was connected, nor Wi-Fi was up.

@CrashSerious - I really have no control on the payload. It is all stored inside "PS3USBJAILBREAK.EXE" executable from www.ps3usbjailbreak.com. I just connect the JB-USB stick to the PC, Choose "KaKaRoTo PL3 of PSGroove for 3.21" from the drop-down menu & click START. Moments later it says some thing like flashed successfully. Only the guy at ps3usbjailbreak.com who compiled & built the flashing tool would know, what hex he chose ....

And then I was thinking of staying with 3.21 for a little longer, because I did not want to regret later if something new surfaces up that says <=3.21. Mostly I am wrong, as 3.41 is ruling the roost everywhere. Hopefully we will have the downgrade or CFW worked out by the community in the exciting days ahead!!
